In [ ]:
import numpy as np 

Primera Parte

In [ ]:
#Encuentra el maximo de los elementos en una columna.
def Max(p,n, in_aux):
  max = p[0]
  ind = in_aux
  for i in range(1,n):
    if p[i]> max:
      max = p[i]
      ind= i+in_aux
  return ind, max
#Algoritmo de factorización LU con pivote parcial.
def factLU(A, n, tao):
  L = np.identity(n)
  U = A.copy()
  ind= 0
  max= 0
  p = np.arange(n)
  for i in range(n):  
    #pivoteo- inicio
    aux= U[i][i:]
    ind,max= Max(aux, aux.size-i, i)
    #Si el elemento más grande es menor a tao, no es posible hacer el algoritmo
    #terminarlo regresando 1
    if np.abs(max)< tao:
      return 1
    if ind != i:
    #Se lleva a cabo el pivote 
      for j in range(n):
        v= U[i][j]
        U[i][j]=U[ind][j]
        U[ind][j]= v
    #Se llena el vector de permutación
      v= p[i]
      p[i]= p[ind]
      p[ind]= v
      if i > 0: 
        for j in range(i):
          v= L[i][j]
          L[i][j]= L[ind][j]
          L[ind][j]= v
    for k in range(i+1,n):
      L[k][i]= U[k][i]/U[i][i]
      for j in range(i,n):
        U[k][j]= U[k][j]- L[k][i]*U[i][j]
  return L, U, p


def forwSubs(Matr, lenMatr, Arrb, tao):
  x= np.zeros(lenMatr)
  if len(Matr[1])!= len(Arrb):
    print("No es un sistema compatible.")
  else:
    x[0]= Arrb[0]/Matr[0][0]
    for i in range(1,lenMatr):
      b=0
      for j in range(i):
        b = b + Matr[i][j]* x[j]
      b= Arrb[i]- b
      x[i]= b/Matr[i][i]
    return x


  
def BackSubs(Matr, lenMatr, Arrb, tao):
  x= np.zeros(lenMatr)
  if len(Matr[1])!= len(Arrb):
    print("No es un sistema compatible.")
  else:
    x[lenMatr-1]= Arrb[len(Arrb)-1]/ Matr[lenMatr-1][lenMatr-1]
    for i in range(lenMatr-2, -1, -1):
      b=0
      for j in range( len(Arrb)-1, i,-1):
        b = b + Matr[i][j]* x[j]
      b= Arrb[i]- b
      x[i]= b/Matr[i][i]
    return x
def CalcularSol(L, U, p, b, n,tao):
  b_hat= b.copy()
  for i in range(n):
    b_hat[i] = b[p[i]]
  y_1= forwSubs(L, n, b_hat, tao)
  x_1= BackSubs(U, n, y_1, tao)
  return x_1

def Error(A,x,b):
  c= np.matmul(A,x)- b
  return np.linalg.norm(c)


In [ ]:
def Test(Direccion1):
  A1 = np.load(Direccion1, encoding='bytes')
  return A1

In [ ]:
em= np.finfo(float).eps
b_1= Test('/content/vecb6.npy')
A= Test('/content/matrizA6.npy')
#print(A,b_1)
L,U,p= factLU(A, 6, em)
x= CalcularSol(L,U,p, b_1, 6, em)
print(Error(A,x,b_1))
print(x)

0.0
[1. 1. 1. 1. 1. 1.]


Segunda Parte 

In [ ]:
def sum(A,i,j):
  c= 0 
  for k in range(j):
    c+=A[i][k]*A[j][k]
  return c
def Fact_Chole(A, n, tao):
  L = np.zeros((n,n))
  for j in range(n):
    L[j][j]= np.sqrt(A[j][j]- sum(L,j,j))
    for i in range(j+1,n):
      L[i][j]= (A[i][j]-sum(L,i,j))/L[j][j]
  return L, L.transpose()

In [ ]:
L, L_T= Fact_Chole(A, 5, em)
p = np.arange(5)
print(CalcularSol(L,L_T,p, b_1,5, em))
print(L)
print(L_T)

[1. 1. 1. 1. 1.]
[[ 1.41421356  0.          0.          0.          0.        ]
 [-1.02601194  1.71677008  0.          0.          0.        ]
 [-0.10040916 -0.71006655  2.34216214  0.          0.        ]
 [-0.09970206  0.19030184 -0.19976586  2.81317229  0.        ]
 [ 0.04101219 -0.10072461  0.43745768 -0.10996618  3.12805223]]
[[ 1.41421356 -1.02601194 -0.10040916 -0.09970206  0.04101219]
 [ 0.          1.71677008 -0.71006655  0.19030184 -0.10072461]
 [ 0.          0.          2.34216214 -0.19976586  0.43745768]
 [ 0.          0.          0.          2.81317229 -0.10996618]
 [ 0.          0.          0.          0.          3.12805223]]
