In [ ]:
import numpy as np 
from google.colab import files

Primera Parte 

Dado que $G(i,j,\theta)$ es una matriz diagonal con 1's en la diagonal excepto en las columnas $i,j$, se sigue que $p_l= v_lg_l = v_i$ con $l\not= i,j$. Ahora, si $l= i$, entonces $p_l= v_icos(\theta)- v_jsin(\theta)$, de manera similar, si $l= j$ entonces $p_l= v_jcos(\theta)+ v_isin(\theta)$

In [ ]:
def product(V, n, i, j, c, s):
  v_i= V[:,i].copy()
  v_j= V[:,j].copy()
  for k in range(n):
    V[k][i]= c*v_i[k]- s*v_j[k]
    V[k][j]= c*v_j[k]+ s*v_i[k]
  return V

Segunda Parte. 

In [24]:
def Grater(V, n):
  indice_i= 1
  indice_j= 0
  sup= np.abs(V[1][0])
  for i in range(1,n):
    for j in range(i):
      if np.abs(V[i][j])> sup:
        sup= np.abs(V[i][j])
        indice_i= i
        indice_j= j
  return sup, indice_i, indice_j

def Jacobi(A, n, tao, M):
  B= A.copy()
  V= np.identity(n)
  for k in range(M):
      bMax, i, j= Grater(B,n)
      if np.abs(bMax) < tao:
        print(k)
        break
      delta = (B[j][j] - B[i][i])/(2* bMax)
      t= np.sign(delta)/(np.abs(delta)+np.sqrt(1+ delta**(2)))
      c= 1/ np.sqrt(1+t**(2))
      s= c*t
      b_i= B[:, i].copy()
      b_j= B[:, j].copy()
      B[i][i]= c**(2)*b_i[i]-2*s*c*b_i[j]+s**(2)*b_j[j]
      B[j][j]= s**(2)*b_i[i]+2*s*c*b_i[j]+c**(2)*b_j[j]
      for l in range(n):
        if l!= i and l!= j:
          B[i][l]= c*b_i[l]-s*b_j[l]
          B[j][l]= s*b_i[l]+c*b_j[l]
          B[l][i]= B[i][l]
          B[l][j]= B[j][l]
      B[i][j], B[j][i]= 0,0 
      print(i,j, bMax)
      V= product(V, n, i, j, c, s)
      print(B)
  return  V
em= np.finfo(float).eps
tao= em**(1/2)
M= 100*9

In [ ]:
matr= np.array([[2.0,1.0,-1.0],[1.0,5.0,-2.0],[-1.0,-2.0,4.0]])
Jacobi(matr, 3, tao, M)


2 1 2.0
[[ 2.          0.17279323 -1.40361765]
 [ 0.17279323  2.68098281  0.        ]
 [-1.40361765  0.          6.31901719]]
2 0 1.403617647418745
[[3.11378944 0.16566784 0.        ]
 [0.16566784 2.68098281 0.04910874]
 [0.         0.04910874 5.20522775]]
1 0 0.16566783543308347
[[3.16992278 0.         0.01575948]
 [0.         2.62484948 0.04651137]
 [0.01575948 0.04651137 5.20522775]]
2 1 0.04651136529206214
[[ 3.16992278e+00 -2.83926502e-04  1.57569173e-02]
 [-2.83926502e-04  2.62401138e+00  0.00000000e+00]
 [ 1.57569173e-02  0.00000000e+00  5.20606584e+00]]
2 0 0.01575691727447056
[[ 3.16980085e+00 -2.83918002e-04  0.00000000e+00]
 [-2.83918002e-04  2.62401138e+00 -2.19699915e-06]
 [ 0.00000000e+00 -2.19699915e-06  5.20618777e+00]]
1 0 0.00028391800212369936
[[ 3.16980040e+00  0.00000000e+00 -1.14287174e-09]
 [ 0.00000000e+00  2.62401182e+00 -2.19699886e-06]
 [-1.14287174e-09 -2.19699886e-06  5.20618777e+00]]
2 1 2.1969988559335693e-06
[[ 3.16980040e+00  9.72392256e-16 -1.14287174e

array([[ 0.90570834, -0.31321839,  0.28563376],
       [ 0.4234162 ,  0.70068734, -0.57424383],
       [-0.02027623,  0.64103938,  0.76724011]])