In [ ]:
import numpy as np
from numpy import linalg as LA

Primera parte 

In [ ]:
def interv(a, b, n, m):
  x= np.linspace(a, b, m)
  matr= np.zeros((m,n))
  for i in range(n):
    matr[:,i]= x**(i)
  return matr

Segunda Parte 

In [ ]:
def Decomp(A, m, n, tao, N):
  em= np.finfo(float).eps
  k = 0
  F = 1
  s_1 = (n,n)
  ns= np.zeros(n)
  V= np.zeros(s_1)
  for q in range(n):
    V[q][q]= 1
  while k < N and F>0:
    k = k+1
    F=0
    for i in range(0,n):
      for j in range(i, n):
        alpha= np.matmul(A[:,i],A[:,i])
        gamma= np.matmul(A[:,j],A[:,j])
        beta= np.matmul(A[:,i],A[:,j])
        if alpha*gamma> em and np.abs(beta)>tao*alpha*gamma:
          F = 1
          if beta != 0:
            nu = (gamma - alpha)/(2*beta)
            t = 1/(np.abs(nu)+ np.sqrt(1+nu**(2)))
            if nu < 0:
              t = -t
            c = 1/(1+t**(2))
            s = t*c 
          else:
            c = 1
            s = 0
            t = 0
          a = A[:, i].copy()
          b = A[:, j].copy()
          A[:, i]= c*a - s*b
          A[:, j]= s*a + a*b
          a = V[:, i].copy()
          b = V[:, j].copy()
          V[:, i]= c*a- s*b
          V[:, j]= s*a + c*b
  for j in range(n):
    ns[j]= np.linalg.norm(A[:, j])
  ns1= np.sort(ns)
  for i in range(n):
    for j in range(i, n):
      if ns[j] == ns1[i]:
        y= A[:,j]
        A[:, i]= y
        A[:, j]= A[:, i]
        y= V[:,j]
        V[:, i]= y
        V[:, j]= V[:, i]
  U= np.zeros((n,m))
  for j in range(n):
    U[:, j]= A[:, j]/ ns1[j]
  return U, V, ns

def Prob(A, lenA):
  em= np.finfo(float).eps
  S= np.identity(lenA)
  print(lenA)
  U,V, ns= Decomp(A,lenA,lenA, em, 100)
  print(LA.norm(np.identity(lenA)-np.matmul(U.transpose(),U)))
  print(LA.norm(np.identity(lenA)-np.matmul(V.transpose(),V)))
  for i in range(lenA):
    S[i][i]= ns[i]
  print(U,V,ns,S)
  S= np.matmul(U,S)
  S= np.matmul(S,V.transpose())
  print(LA.norm(A-S))
A= np.array([[2.0,1.0,-1.0],[1.0,5.0,-2.0],[-1.0,-2.0,4.0]])
Prob(A, 3)


3
1.0000496706556594
1.1536017686545579
[[ 2.41732309e-06  1.00000000e+00  2.41334152e-07]
 [-1.00000000e+00  2.45882365e-05 -9.98352899e-02]
 [ 6.95359205e-23  8.07377436e-17  6.94213879e-24]] [[-0.04375501  0.49812952 -0.04375501]
 [-0.36067988  0.3586638  -0.36067988]
 [ 0.68597499  0.32430587  0.68597499]] [3.75532676e+13 5.96850587e+12 3.74914136e+12] [[3.75532676e+13 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 5.96850587e+12 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 3.74914136e+12]]
27193680027765.81
